/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useRecoilState } from "recoil";
import { playerPosition } from "../atoms";

export default function Model({ action }) {
  const [playPosition, setPlayPosition] = useRecoilState(playerPosition);

  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/michel.glb");

  const { actions } = useAnimations(animations, group);
  const previousAction = usePrevious(action);

  useEffect(() => {
    console.log("actions", actions);
    if (previousAction) {
      actions[previousAction].fadeOut(0.2);
      actions[previousAction].stop();
    }
    actions[action].play();
    actions[action].fadeIn(0.2);
    setPlayPosition(group.current.position);
    console.log("group.current.position", playPosition);
  }, [action, actions, previousAction]);

  return (
    <group ref={group} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            castShadow
            name="Ch03"
            geometry={nodes.Ch03.geometry}
            material={materials.Ch03_Body}
            skeleton={nodes.Ch03.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/michel.glb");

function usePrevious(value) {
  const ref = useRef();
  useEffect(() => {
    ref.current = value;
  }, [value]);
  return ref.current;
}
